# Configuration/Dashboards for grafana #

## Apache Requests ##

### 404 Requests ###
#
SELECT count("request")
FROM "apache_access_log"
WHERE "host" =  'ubuntu-bionic'
  AND "resp_code" = '404'
  AND $timeFilter 
  AND "agent" != 'Go-http-client/1.1'
  AND agent != 'worldping-api'

### Logs ###

SELECT  "request"
FROM "apache_access_log"
WHERE "host" =~ /^$server$/ 
  AND "resp_code" =~ /^$code$/ 
  AND $timeFilter  

SELECT  "client_ip"
FROM "apache_access_log"
WHERE "host" =~ /^$server$/ 
  AND "resp_code" =~ /^$code$/ 
  AND $timeFilter  
