- hosts: terraform-ansible
  tasks:
    - name: "create archive"
      copy:
        dest: "/home/ubuntu/index.html"
        content: "<h1>Done with terraform and ansible withou love.</h1><p>Just tears...</p>"
    - name: "create server"
      shell: "nohup busybox httpd -f -p 8080 &"
