- hosts: terraform-ansible
  tasks:
    - name: "Install python3 and virtualenv"
      apt:
        pkg:
          - python3
          - virtualenv
          update_cache: yes
      become: yes
    - name: "Install dependencies with pip - Django and Django Rest"
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestfrmework
    - name: "Starting django project"
      shel: ". /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc"
      ignore_errors: yes
    - name: "Changing hosts in settings.py"
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
