class_01-07:
	terraform init
	terraform plan
	terraform apply

class_02-04:
	terraform show

class _02-06:
	aws ec2 describe-security-group

class_06-02:
	terraform destroy --target aws_s3_bucket.bkt01
#	terraform destroy

class_06-04:
	terraform refresh

get_all_contents:
	wget https://cdn3.gnarususercontent.com.br/1308-terraform/07/aula-7-completa.zip 
