---
- name: 'Download Wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
    mode: 0777

- name: 'Unpack Wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes
  
- name: 'Copy Configuration File for Wordpress'
  copy:
    src: "{{ app_installation_dir }}/wp-config-sample.php"
    dest: "{{ app_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Replace Config File with Correct Data'
  replace:
    path: "{{ app_installation_dir }}/wp-config.php"
    regexp: '{{ item.regex }}'
    replace: '{{ item.value }}'
    backup: yes
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{ wp_user_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
  become: yes
  notify:
    - 'Setup Apache2'  
