apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-news-deployment
spec:
  selector:
    matchLabels:
      name: backend-news-pod
  template:
    metadata:
      labels:
        name: backend-news-pod
    spec:
      containers:
        - name: container-backend
          # image: jnlucas/image-phpmysql:latest
          image: foguinhoperuca/alura-news-backend:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
