apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-news-deployment
spec:
  selector:
    matchLabels:
      name: sys-news-pod
  template:
    metadata:
      labels:
        name: sys-news-pod
    spec:
      containers:
        - name: container-sys
          # image: jnlucas/image-phpmysql:latest
          image: foguinhoperuca/alura-news-sys:v1
          ports:
            - containerPort: 80
