---
- name: 'Install dependencies'
  apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: latest
  become: yes
- name: 'Conf MySQL DB'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes
- name: 'Create database user'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL,GRANT"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ db_host_ip }}"
    - "{{ app_ip }}"
  become: yes
- name: 'Configure MySQL to accept remote connections'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - 'Restart MySQL'
