server {
    listen 2020;
    root /var/www/alura-performance.jeffersoncampos.eti.br;
}

server {
    listen 3030;
    root /var/www/alura-performance.jeffersoncampos.eti.br;
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
