fastcgi_cache_path /tmp/cache_nginx_alura levels=1:2 keys_zone=fpm:10m;

server {
    listen 8005;
    root /fast_cgi;

    location / {
        include /etc/nginx/fastcgi.conf;
        fastcgi_pass localhost:9000;
        fastcgi_cache_key $request_method$request_uri;
        fastcgi_cache fpm;
        fastcgi_cache_valid 1m;
        add_header X-Cache-Status $upstream_cache_status;
    }
}
