upstream alura-backup {
    server nginx-devops-alura-service01.jeffersoncampos.eti.br:8001 fail_timeout=60s;
    server nginx-devops-alura-service02.jeffersoncampos.eti.br:8002 backup;
}

server {
    listen 8004;
    server_name nginx-devops-alura-backup.jeffersoncampos.eti.br;

    location / {
        proxy_pass http://alura-backup;
        proxy_set_header X-CUSTOM-Real-IP $remote_addr;
        # health_check;
    }
}
