server {
    #listen 8007;
    listen 443 ssl; # important set ssl here after 443
    server_name nginx-devops-alura-https.jeffersoncampos.eti.br;
    root /home/jecampos/universal/projects/study/alura/devops/alura-shell-script-devops/nginx/https/;
    index index.html;
    ssl_certificate /tmp/localhost.crt;
    ssl_certificate_key /tmp/localhost.key;
}
