upstream alura {
    server nginx-devops-alura-service01.jeffersoncampos.eti.br:8001 weight=4;
    server nginx-devops-alura-service02.jeffersoncampos.eti.br:8002 weight=2;
}

server {
    listen 8003;
    server_name nginx-devops-alura-loadbalancer.jeffersoncampos.eti.br;

    location / {
        proxy_pass http://alura;
        proxy_set_header X-CUSTOM-Real-IP $remote_addr;
    }
}
