server {
    listen 8080;
    listen [::]:8080;
    server_name nginx-devops-alura-api-gateway.jeffersoncampos.eti.br;
    root /var/www/nginx-devops-alura-api-gateway.jeffersoncampos.eti.br;
    location /service01/ {
        proxy_pass http://nginx-devops-alura-service01.jeffersoncampos.eti.br:8001/;
    }
    location /service02/ {
        proxy_pass http://nginx-devops-alura-service02.jeffersoncampos.eti.br:8002/;
    }
}

server {
    listen 8001;
    listen [::]:8001;
    server_name nginx-devops-alura-service01.jeffersoncampos.eti.br;
    access_log /var/log/nginx/nginx-devops-service01.jeffersoncampos.eti.br_access.log alura_log;
    location / {
        root /var/www/nginx-devops-alura-service01.jeffersoncampos.eti.br;
        index index.html;
    }
}

server {
    listen 8002;
    listen [::]:8002;
    server_name nginx-devops-alura-service02.jeffersoncampos.eti.br;
    access_log /var/log/nginx/nginx-devops-service02.jeffersoncampos.eti.br_access.log alura_log;
    location / {
        root /var/www/nginx-devops-alura-service02.jeffersoncampos.eti.br;
        index index.html;
    }
}
