server {
    listen 8006;
    server_name nginx-devops-alura-performance.jeffersoncampos.eti.br;
    root /home/jecampos/universal/projects/study/alura/devops/alura-shell-script-devops/nginx/performance/;
    index index.html;
    gzip on;
    gzip_types text/css;
    add_header Keep-Alive "timeout=5, max=1000";

    location ~ \.jpg$ {
        expires 30d;
        add_header Cache-Control public;
    }
}
