server {
    listen 8080;
    server_name nginx-devops-alura-webserver.jeffersoncampos.eti.br;

    location ~ \.php$ {
        proxy_pass http://localhost:8000;
    } 

    location / {
        # Could be a reverse proxy:
        # proxy_pass http://localhost;
        root /var/www/nginx-devops-alura-webserver.jeffersoncampos.eti.br;
        index index.html;
    }
}
