---
- hosts: all
  tasks:
    - name: 'Install dependencies'
      apt:
        name:
          - git
          - apache2
          - php
          - libapache2-mod-php
          - php-gd
          # - php-ssh2
          # - php-mcrypt
          - mysql-server
          - python3-mysqldb
          - php-mysql
        state: latest
      become: yes
    - name: 'Conf MySQL DB'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: absent
      become: yes
