---
- hosts: all
  tasks:
    # - shell: 'echo hello > /home/vagrant/universal/output/world.txt'
    - name: 'Custom install for php'
      apt:
        name: php
        state: latest
      become: yes
    - name: 'mod php for apache'
      apt:
        name: libapache2-mod-php
        state: latest
      become: yes
    - name: 'Install Python'
      apt:
        name: python3
        state: latest
      become: yes
    - name: 'Install Apache 2'
      apt:
        name: apache2
        state: latest
      become: yes
      
