---
- hosts: all
  handlers:
    - name: 'Restart Apache2'
      service:
        name: apache2
        state: restarted
      become: yes
      listen: 'Setup Apache2'
  tasks:
    - name: 'Install dependencies'
      apt:
        name:
          - git
          - apache2
          - php
          - libapache2-mod-php
          - php-gd
          # - php-ssh2
          # - php-mcrypt
          - mysql-server
          - python3-mysqldb
          - php-mysql
        state: latest
      become: yes
    - name: 'Conf MySQL DB'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes
    - name: 'Create database user'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 'A12345678a'
        priv: 'wordpress_db.*:ALL,GRANT'
        state: present
      become: yes
    - name: 'Download Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
        mode: 0777
    - name: 'Unpack Wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes
    - name: 'Copy Configuration File for Wordpress'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes
    - name: 'Replace Config File with Correct Data'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'password_here', value: 'A12345678a' }
      become: yes
    - name: 'Copy Apache Configuration File'
      copy:
        src: 'conf_files/wordpress.conf'
        dest: '/etc/apache2/sites-available/wordpress.conf'
      become: yes
      notify:
        - 'Setup Apache2'
    - name: 'Enabling Wordpress Site'
      shell: /usr/sbin/a2ensite wordpress.conf
      become: yes
      notify: 'Setup Apache2'
