---
- hosts: all
  tasks:
    - name: 'Install dependencies'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - apache2
        - php
        - libapache2-mod-php
        - php-gd
        - php-ssh2
        # - php-mcrypt
        - mysql-server
        - python3-mysqldb
        - php-mysql
