Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # alternatives: ubuntu/kinetic64 and ubuntu/lunar64
  config.vm.box_download_insecure = true

  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
  end

  config.vm.define "wordpress" do |m|
    m.vm.network "private_network", ip: "192.168.56.101" # alternative 172.16.1.98
  end

  config.vm.define "mysql" do |m|
    m.vm.network "private_network", ip: "192.168.56.102" # alternative 172.16.1.99
  end

end
